hostname l1-frr
!
interface lo
 ip address 10.255.9.3/32
 ip router isis LAB
 isis passive
!
interface eth1
 ip address 10.1.3.2/30
 ip router isis LAB
 isis circuit-type level-1
 isis network point-to-point
 no isis hello padding
!
interface eth2
 ip address 10.2.3.2/30
 ip router isis LAB
 isis circuit-type level-1
 isis network point-to-point
 no isis hello padding
!
interface eth3
 ip address 10.3.3.2/30
 ip router isis LAB
 isis circuit-type level-1
 isis network point-to-point
 no isis hello padding
!
router isis LAB
 net 49.0011.0000.0009.0003.00
 is-type level-1
 metric-style wide
!
