hostname frr-border
!
interface lo
 ip address 10.255.2.1/32
 ip router isis LAB
 isis passive
!
interface eth1
 ip address 10.2.0.2/30
 ip router isis LAB
 isis circuit-type level-2-only
 isis network point-to-point
 no isis hello padding
!
interface eth2
 ip address 10.2.1.1/30
 ip router isis LAB
 isis circuit-type level-1
 isis network point-to-point
 no isis hello padding
!
interface eth3
 ip address 10.2.2.1/30
 ip router isis LAB
 isis circuit-type level-1
 isis network point-to-point
 no isis hello padding
!
interface eth4
 ip address 10.2.3.1/30
 ip router isis LAB
 isis circuit-type level-1
 isis network point-to-point
 no isis hello padding
!
router isis LAB
 net 49.0012.0000.0002.0001.00
 is-type level-1-2
 metric-style wide
!
