version 23.4R2-S6.9;
system {
    host-name border-junos;
    root-authentication {
        encrypted-password "$6$APKoGjlf$eqyC5C5kHcWU7OWRy3J9ftfZJ/AMsROvDTT/NV4RelyhwGf0vpjgm42rKNk3weKEkm4kk4A5TIzlIZOJcQQUm/"; ## SECRET-DATA
    }
    login {
        user admin {
            uid 2000;
            class super-user;
            authentication {
                encrypted-password "$6$O7juqF0W$Sq1Qi4.G1UQHnRn7FLjEZM8KgC7nW40babgsBo3f631SKlb3G9E3gk7T4h9.KaW1jIms9E5h8V/lQetEgJhAi/"; ## SECRET-DATA
            }
        }
    }
    services {
        netconf {
            ssh;
        }
        ssh {
            root-login allow;
        }
    }
    management-instance;
}
chassis {
    fpc 0 {
        pic 0 {
            number-of-ports 12;
        }
    }
}
interfaces {
    ge-0/0/0 {
        unit 0 {
            family inet {
                address 10.3.0.2/30;
            }
            family iso;
        }
    }
    ge-0/0/1 {
        unit 0 {
            family inet {
                address 10.3.1.1/30;
            }
            family iso;
        }
    }
    ge-0/0/2 {
        unit 0 {
            family inet {
                address 10.3.2.1/30;
            }
            family iso;
        }
    }
    ge-0/0/3 {
        unit 0 {
            family inet {
                address 10.3.3.1/30;
            }
            family iso;
        }
    }
    fxp0 {
        unit 0 {
            family inet {
                address 10.0.0.15/24;
            }
            family inet6 {
                address 2001:db8::2/64;
            }
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 10.255.3.1/32;
            }
            family iso {
                address 49.0011.0000.0003.0001.00;
            }
        }
    }
}
routing-instances {
    mgmt_junos {
        routing-options {
            rib mgmt_junos.inet6.0 {
                static {
                    route ::/0 next-hop 2001:db8::1;
                }
            }
            static {
                route 0.0.0.0/0 next-hop 10.0.0.2;
            }
        }
    }
}
protocols {
    isis {
        interface ge-0/0/0.0 {
            point-to-point;
            level 1 disable;
        }
        interface ge-0/0/1.0 {
            point-to-point;
            level 2 disable;
        }
        interface ge-0/0/2.0 {
            point-to-point;
            level 2 disable;
        }
        interface ge-0/0/3.0 {
            point-to-point;
            level 2 disable;
        }
        interface lo0.0 {
            passive;
        }
        level 1 wide-metrics-only;
        level 2 wide-metrics-only;
    }
}
